name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: CHeckout
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            # Navigate to the project directory
            cd /var/www/your-repo

            # Pull the latest changes
            git pull origin main

            # Install dependencies
            npm install --legacy-peer-deps

            # Build the Next.js app
            npm run build

            # Restart the app using PM2
            pm2 restart kampair || pm2 start npm --name "kampair" -- start -- --dotenv .env
          EOF
