name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            # Navigate to the project directory
            cd /kampair

            # Pull the latest changes from GitHub
            git pull origin main

            # Install dependencies
            npm install --legacy-peer-deps

            # Run PM2 deploy command to deploy the app based on the ecosystem config file
            npx pm2 deploy ecosystem.config.cjs production
          EOF
